#!/bin/bash -eu

# Provisions a Machine From Scratch

set -o pipefail

if ${trace:-false}; then
  set -x
fi

packages=(git vim)

provision-machine() {
  create-development-directory
  install-nix
  install-or-upgrade-packages
}

create-development-directory() {
  if development-directory-doesnt-exist; then
    echo "Creating Development Directory ..."
    mkdir ~/Development
  fi
}

development-directory-doesnt-exist() {
  test ! -d ~/Development
}

install-nix() {
  if nix-env-isnt-installed; then
    echo "Installing Nix Package Manager ..."
    curl https://nixos.org/nix/install | sh
  fi
}

nix-env-isnt-installed() {
  test `which -s nix-env`
}

install-or-upgrade-packages() {
  for package in ${packages[@]}; do
    install_or_upgrade $package
  done 
}

install_or_upgrade() {
 if package-isnt-installed $1; then
   install $1
 else
   upgrade $1
 fi
}

package-isnt-installed() {
  test `nix-env -q $1 > /dev/null`
}

install() {
  echo "Installing $1 ..."
  nix-env -i $1
}

upgrade() {
  echo "Upgrading $1 ..."
  nix-env -u $1
}

provision-machine
